### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by emagomez99** [gabriel-fabian/cuex#7]
Good morning.

I was making some "post" requests at https://cuex-app.herokuapp.com/api/convert  .

However now it returns error **403** "Too Many Requests" :

"Your monthly usage limit has been reached. Please upgrade your Subscription Plan."

How can I solve this?

I was completing a challenge for a job interview.

I hope you can help me, thank you

**Comment by gabriel-fabian** [comment]
Hi @emagomez99.

This project was made using a free API plan which has a limit of 1k requests/month. Only upgrading this plan can fix this.

Is there any other way i can reach you besides this GItHub Issue? So that i can understand your challenge and try to help in other way

**Comment by gabriel-fabian** [comment]
Hi @emagomez99 

I've sent you an email about this topic
